# Site settings
title:       LinuxGit
email:       gofaceme#gmail.com
author:      Louis Liu
description: "About learning, reading and life."
baseurl:     ""
url:         "http://linuxgit.org"
timezone: Asia/Beijing

# Google analytics
google_analytics: 

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: Louis

# Social icons
show_social_icons: true
github_username: LinuxGit
dribbble_username: 
stackoverflow_id:
twitter_username: LinuxGit
linkedin_username: 
weibo_id: 1906750863
instagram_username: 
behance_id: 


# Build settings
permalink:    pretty
paginate:     5
paginate_path: "/page:num/"
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
